### ISSUE TITLE
sdgFormatted missing variable 'headspaceTemp'

### ISSUE THREAD

**Issue by jhart6** [NEONScience/NEON-dissolved-gas#16]
Hello! I am just getting started learning how to use the functions provided in this package to increase efficiency processing large quantities of GC data. Love this package!

I noticed that the sdgFormatted.rda, which I downloaded directly from Github, was missing the "headspaceTemp" variable column. This column appears to be a requirement for running the def.calc.sdg.conc() function. It was easy enough to append fake headspace temperatures for the sake of learning the package, but might be something helpful to include for future users.

Apologies if this is actually not a bug, and just a deficit in my own coding abilities. Thanks for writing such an amazingly well-documented and commented package!

**Comment by kcawley** [comment]
@jhart6 Thanks for taking the time to make an issue. I've updated the data description and file to include headspaceTemp. Let me know if you have any other trouble with the package!
